export const QUERY_KEYS = {

    AUTH: {
        USER_INFO: "USER_INFO",
    },
    TOUR:
    {
        LIST_TOUR: "LIST_TOUR",
        DETAIL_TOUR: "DETAIL_TOUR",
        LIST_TOUR_PUBLISH: "LIST_TOUR_PUBLISH",
        LIST_TOUR_DAY: "LIST_TOUR_DAY",
        LIST_PARTNER: "LIST_PARTNER",
    },
    HOTEL: {
        LIST_HOTEL: "LIST_HOTEL",
        LIST_ITEM_BY_AGENT: "LIST_ITEM_BY_AGENT"
    },
    COMPANY_OWNER: {
        LIST_COMPANY_OWNER: "LIST_COMPANY_OWNER",
        LIST_COMPANY_DES_DAY: "LIST_COMPANY_DES_DAY",
    },
    VEHICLE: {
        LIST_VEHICLE: "LIST_VEHICLE",
    },
    FLIGHT: {
        LIST_FLIGHT: "LIST_FLIGHT",
    },
    RESTAURANT: {
        LIST_RESTAURANT: "LIST_RESTAURANT",
    },
    GUIDE_FEE: {
        LIST_GUIDE_FEE: "LIST_GUIDE_FEE",
    },

};
