export const QUERY_KEYS = {

    AUTH: {
        USER_INFO: "USER_INFO",
    },
    TOUR:
    {
        LIST_TOUR: "LIST_TOUR",
        DETAIL_TOUR: "DETAIL_TOUR",
        LIST_TOUR_PUBLISH: "LIST_TOUR_PUBLISH",
        LIST_TOUR_DAY: "LIST_TOUR_DAY",
        LIST_PARTNER: "LIST_PARTNER",
    },
    HOTEL: {
        LIST_HOTEL: "LIST_HOTEL",
        LIST_ITEM_BY_AGENT: "LIST_ITEM_BY_AGENT"
    },
    BOAT: {
        LIST_BOAT: "LIST_BOAT",
        LIST_IMAGE: "LIST_IMAGE",
        LIST_MAPPING_PRICE: "LIST_MAPPING_PRICE",
    },
    COMPANY_OWNER: {
        LIST_COMPANY_OWNER: "LIST_COMPANY_OWNER",
        LIST_COMPANY_DES_DAY: "LIST_COMPANY_DES_DAY",
    },
    VEHICLE: {
        LIST_VEHICLE: "LIST_VEHICLE",
        DETAI_VEHICLE: "DETAIL_VEHICLE",
        LIST_MAPPING_PRICE:"LIST_MAPPING_PRICE",
    },
    FLIGHT: {
        LIST_FLIGHT: "LIST_FLIGHT",
        DETAIL_FLIGHT: "DETAIL_FLIGHT",
        LIST_MAPPING_PRICE: "LIST_MAPPING_PRICE",
    },
    RESTAURANT: {
        LIST_RESTAURANT: "LIST_RESTAURANT",
        DETAIL_RESTAURANT: "DETAIL_RESTAURANT",
        LIST_MAPPING_PRICE: "LIST_MAPPING_PRICE",
        LIST_IMAGE: "LIST_IMAGE",

    },
    GUIDE_FEE: {
        LIST_GUIDE_FEE: "LIST_GUIDE_FEE",
        DETAIL_GUIDE_FEE: "DETAIL_GUIDE_FEE",
        LIST_MAPPING_PRICE: "LIST_MAPPING_PRICE",
    },

};
